version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - FRONTEND_PORT=8501
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: streamlit run app/app.py --server.port 8501 --server.address 0.0.0.0 