version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-text-processor-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_MODEL=${AI_MODEL:-gemini-2.0-flash-exp}
      - AI_TEMPERATURE=${AI_TEMPERATURE:-0.7}
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_ORIGINS=["http://localhost:8501", "http://frontend:8501"]
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    networks:
      - ai-processor-network
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-text-processor-frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
      - SHOW_DEBUG_INFO=${SHOW_DEBUG_INFO:-false}
      - MAX_TEXT_LENGTH=${MAX_TEXT_LENGTH:-10000}
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    networks:
      - ai-processor-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: ai-text-processor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-processor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ai-text-processor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - ai-processor-network
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

volumes:
  redis_data:

networks:
  ai-processor-network:
    driver: bridge 