# mkdocs.yml in the project root directory

site_name: AI Text Processor Documentation
site_description: API Reference and Guides for the FastAPI-Streamlit-LLM Application
# site_url: https://your-docs-url.com # Replace with your actual documentation URL
repo_url: https://github.com/matthannigan/fastapi-streamlit-llm-starter # Replace with your repository URL
repo_name: GitHub

nav:
  - Home: index.md
  - API Reference:
      - Backend: api_reference/backend.md
      - Shared Models: api_reference/shared.md
      - API Documentation: API.md
  - Getting Started:
      - Authentication: AUTHENTICATION.md
      - Advanced Auth Guide: ADVANCED_AUTH_GUIDE.md
      - Integration Guide: INTEGRATION_GUIDE.md
      - Virtual Environment Guide: VIRTUAL_ENVIRONMENT_GUIDE.md
  - Development:
      - Code Standards: CODE_STANDARDS.md
      - Testing: TESTING.md
      - Documentation Guidance: DOCUMENTATION_GUIDANCE.md
      - Template Customization: TEMPLATE_CUSTOMIZATION.md
      - Checklist: CHECKLIST.md
  - Architecture & Design:
      - Infrastructure vs Domain: INFRASTRUCTURE_VS_DOMAIN.md
      - Standardization Summary: STANDARDIZATION_SUMMARY.md
      - Frontend Standardization: FRONTEND_STANDARDIZATION.md
  - Infrastructure:
      - Cache: CACHE.md
      - Security: SECURITY.md
      - Resilience Config: RESILIENCE_CONFIG.md
      - Resilience Integration: RESILIENCE_INTEGRATION.md
  - Deployment:
      - Docker: DOCKER.md
      - Deployment Guide: DEPLOYMENT.md
  - Examples: examples/README.md

docs_dir: docs
site_dir: docs-website

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - backend # Point to your backend directory
            - shared # Point to your shared directory  
          options:
            show_source: false # Do not show source code in generated docs
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false # Don't show members without docstrings
            docstring_style: google # Or numpy, or restructuredtext
            members_order: alphabetical
            separate_signature: true
            merge_init_into_class: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
