import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Organized sidebar for the FastAPI + Streamlit LLM Starter Template documentation
 */
const sidebars: SidebarsConfig = {

  docs: [
    {
      type: 'doc',
      id: 'README',
      label: 'About the Template',
    },
    { // Get Started
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        title: 'Get Started',
        //description: 'Learn how to get started with the FastAPI + Streamlit LLM Starter Template!',
        slug: '/get-started',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'get-started/SETUP_INTEGRATION',
          label: 'Setup & Complete Systems Integration Guide',
        },
        {
          type: 'doc',
          id: 'get-started/CHECKLIST',
          label: 'Checklist',
        },
      ],
    },
    { // Key Concepts
      type: 'category',
      label: 'Key Concepts',
      link: {
        type: 'generated-index',
        title: 'Key Concepts',
        //description: '',
        slug: '/reference/key-concepts',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/key-concepts',
        },
      ],
    },
    { // Guides
      type: 'category',
      label: 'Comprehensive Guides',
      link: {
        type: 'generated-index',
        title: 'Comprehensive Guides',
        slug: '/guides',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/BACKEND',
          label: 'FastAPI Backend',
        },
        {
          type: 'doc',
          id: 'guides/API',
          label: 'API Documentation',
        },
        {
          type: 'category',
          label: 'Infrastructure Services',
          link: {
            type: 'generated-index',
            title: 'Infrastructure Services',
            slug: '/guides/infrastructure',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/infrastructure',
            },
          ],
        },
        {
          type: 'doc',
          id: 'guides/FRONTEND',
          label: 'Streamlit Frontend',
        },
        {
          type: 'doc',
          id: 'guides/SHARED',
          label: 'Shared Module',
        },
        {
          type: 'doc',
          id: 'guides/TESTING',
          label: 'Testing',
        },
        {
          type: 'doc',
          id: 'guides/DEPLOYMENT',
          label: 'Deployment',
        },
        {
          type: 'doc',
          id: 'guides/CUSTOMIZATION',
          label: 'Customization',
        },
      ],
    },
    { // Developer Guide
      type: 'category',
      label: 'Developer Guidance',
      link: {
        type: 'generated-index',
        title: 'Developer Guidance',
        slug: '/guides/developer',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/developer',
        },
      ],
    },
    { // Developer Guide
      type: 'category',
      label: 'Future Features',
      link: {
        type: 'generated-index',
        title: 'Future Features',
        description: 'Roadmaps for planned future features of the template or strategies to extend template for production use.',
        slug: '/future-features',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'future-features',
        },
      ],
    },
    { // Additional Documentation Ideas
      type: 'doc',
      id: 'DOCS_MORE',
      label: 'Additional Documentation',
    },
    { // Documentation Indexes
      type: 'category',
      label: 'Documentation Index',
      link: {type: 'doc', id: 'DOCS_INDEX'},
      items: [
        {
          type: 'doc',
          id: 'DOCS_BY_TOPIC',
          label: 'By Topic',
        },
        {
          type: 'doc',
          id: 'DOCS_BY_AUDIENCE',
          label: 'By Audience',
        },
      ],
    },
  ],
  deep_dives: [
    {
      type: 'category',
      label: 'Technical Deep Dives',
      link: {
        type: 'generated-index',
        title: 'Technical Deep Dives',
        slug: '/reference/deep-dives',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/deep-dives',
        },
      ],
    },
  ],
  code_ref: [
    { // Backend
      type: 'category',
      label: 'Backend',
      link: {
        type: 'generated-index',
        title: 'Backend Code Reference',
        slug: '/code_ref/backend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/backend',
        },
      ],
    },
    { // Frontend
      type: 'category',
      label: 'Frontend',
      link: {
        type: 'generated-index',
        title: 'Frontend Code Reference',
        slug: '/code_ref/frontend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/frontend',
        },
      ],
    },
    { // Shared
      type: 'category',
      label: 'Shared',
      link: {
        type: 'generated-index',
        title: 'Shared Module Code Reference',
        slug: '/code_ref/shared',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/shared/shared',
        },
      ],
    },
    { // Examples
      type: 'category',
      label: 'Examples',
      link: {type: 'doc', id: 'code_ref/examples/index'},
      items: ['code_ref/examples/basic_usage.py', 'code_ref/examples/custom_operation.py'],
    },
    { // Scripts
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts Code Reference',
        slug: '/code_ref/scripts',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/scripts',
        },
      ],
    },
  ],
};

export default sidebars;
