import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Organized sidebar for the FastAPI + Streamlit LLM Starter Template documentation
 */
const sidebars: SidebarsConfig = {

  docs: [
    {
      type: 'doc',
      id: 'README',
      label: 'About the Template',
    },
    { // Get Started
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        title: 'Get Started',
        //description: 'Learn how to get started with the FastAPI + Streamlit LLM Starter Template!',
        slug: '/get-started',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'get-started/SETUP_INTEGRATION',
          label: 'Setup & Complete Systems Integration Guide',
        },
        {
          type: 'doc',
          id: 'get-started/CHECKLIST',
          label: 'Checklist',
        },
      ],
    },
    { // Template Components
      type: 'category',
      label: 'Template Explainer',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'reference/key-concepts/DUAL_API_ARCHITECTURE',
          label: 'Dual API Architecture',
        },
        {
          type: 'doc',
          id: 'reference/key-concepts/INFRASTRUCTURE_VS_DOMAIN',
          label: 'Infrastructure vs Domain Services',
        },
        { // Infrastructure Services
          type: 'category',
          label: 'Built-in Infrastructure Services',
          link: {
            type: 'generated-index',
            title: 'Infrastructure Services',
            slug: '/guides/infrastructure',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/infrastructure',
            },  
          ],
        },
        { // Domain Services
          type: 'category',
          label: 'Example Domain Services',
          link: {
            type: 'doc',
            id: 'guides/domain-services/README',
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'guides/domain-services/TEXT_PROCESSING',
              label: 'Text Processing',
            },
          ],
        },
        { // Customization
          type: 'doc',
          id: 'get-started/TEMPLATE_CUSTOMIZATION',
          label: 'Template Customization Guide',
        },
      ],
    },
    { // Application Guides
      type: 'category',
      label: 'Application Guides',
      link: {
        type: 'generated-index',
        title: 'Application Guides',
        slug: '/guides/application',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'guides/application/API',
          label: 'API Documentation',
        },
        {
          type: 'doc',
          id: 'guides/application/BACKEND',
          label: 'FastAPI Backend',
        },
        {
          type: 'doc',
          id: 'guides/application/FRONTEND',
          label: 'Streamlit Frontend',
        },
        {
          type: 'doc',
          id: 'guides/application/SHARED',
          label: 'Shared Module',
        },
      ],
    },
    { // Developer Guides
      type: 'category',
      label: 'Developer Guides',
      link: {
        type: 'generated-index',
        title: 'Developer Guides',
        slug: '/guides/developer',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/developer',
        },
      ],
    },
    { // Operations Guides
      type: 'category',
      label: 'Operations Guides',
      link: {
        type: 'generated-index',
        title: 'Operations Guides',
        slug: '/guides/operations',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/operations',
        },
      ],
    },
    { // Future Features
      type: 'category',
      label: 'Future Features',
      link: {
        type: 'generated-index',
        title: 'Future Features',
        description: 'Roadmaps for planned future features of the template or strategies to extend template for production use.',
        slug: '/future-features',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'future-features',
        },
      ],
    },
    { // Additional Documentation Ideas
      type: 'doc',
      id: 'DOCS_MORE',
      label: 'Additional Documentation Ideas',
    },
    { // Documentation Indexes
      type: 'category',
      label: 'Documentation Index',
      link: {type: 'doc', id: 'DOCS_INDEX'},
      items: [
        {
          type: 'doc',
          id: 'DOCS_BY_TOPIC',
          label: 'By Topic',
        },
        {
          type: 'doc',
          id: 'DOCS_BY_AUDIENCE',
          label: 'By Audience',
        },
      ],
    },
  ],
  deep_dives: [
    {
      type: 'category',
      label: 'Technical Deep Dives',
      link: {
        type: 'generated-index',
        title: 'Technical Deep Dives',
        slug: '/reference/deep-dives',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/deep-dives',
        },
      ],
    },
  ],
  code_ref: [
    { // Backend
      type: 'category',
      label: 'Backend',
      link: {
        type: 'generated-index',
        title: 'Backend Code Reference',
        slug: '/code_ref/backend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/backend',
        },
      ],
    },
    { // Frontend
      type: 'category',
      label: 'Frontend',
      link: {
        type: 'generated-index',
        title: 'Frontend Code Reference',
        slug: '/code_ref/frontend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/frontend',
        },
      ],
    },
    { // Shared
      type: 'category',
      label: 'Shared',
      link: {
        type: 'generated-index',
        title: 'Shared Module Code Reference',
        slug: '/code_ref/shared',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/shared/shared',
        },
      ],
    },
    { // Examples
      type: 'category',
      label: 'Examples',
      link: {type: 'doc', id: 'code_ref/examples/index'},
      items: ['code_ref/examples/basic_usage.py', 'code_ref/examples/custom_operation.py'],
    },
    { // Scripts
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts Code Reference',
        slug: '/code_ref/scripts',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/scripts',
        },
      ],
    },
  ],
};

export default sidebars;
