import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Organized sidebar for the FastAPI + Streamlit LLM Starter Template documentation
 */
const sidebars: SidebarsConfig = {

  docs: [
    'README',
    { // Get Started
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        title: 'Get Started',
        //description: 'Learn how to get started with the FastAPI + Streamlit LLM Starter Template!',
        slug: '/get-started',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'get-started/SETUP_INTEGRATION',
          label: 'Setup & Complete Systems Integration Guide',
        },
        {
          type: 'doc',
          id: 'get-started/CHECKLIST',
          label: 'Checklist',
        },
      ],
    },
    { // Key Concepts
      type: 'category',
      label: 'Key Concepts',
      link: {
        type: 'generated-index',
        title: 'Key Concepts',
        //description: '',
        slug: '/key-concepts',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'key-concepts',
        },
      ],
    },
    { // Quick Guides
      type: 'category',
      label: 'Quick Guides',
      link: {
        type: 'generated-index',
        title: 'Quick Guides',
        slug: '/quick-guides',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'quick-guides/BACKEND',
          label: 'FastAPI Backend',
        },
        {
          type: 'doc',
          id: 'quick-guides/API',
          label: 'API Documentation',
        },
        {
          type: 'category',
          label: 'Infrastructure Services',
          link: {
            type: 'generated-index',
            title: 'Infrastructure Services',
            slug: '/quick-guides/infrastructure',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'quick-guides/infrastructure',
            },
          ],
        },
        {
          type: 'doc',
          id: 'quick-guides/FRONTEND',
          label: 'Streamlit Frontend',
        },
        {
          type: 'doc',
          id: 'quick-guides/SHARED',
          label: 'Shared Module',
        },
        {
          type: 'doc',
          id: 'quick-guides/TESTING',
          label: 'Testing',
        },
        {
          type: 'doc',
          id: 'quick-guides/DEPLOYMENT',
          label: 'Deployment',
        },
        {
          type: 'doc',
          id: 'quick-guides/CUSTOMIZATION',
          label: 'Customization',
        },
      ],
    },
    { // Developer Guide
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'generated-index',
        title: 'Developer Guide',
        //description: '',
        slug: '/developer-guide',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-guide',
        },
      ],
    },
    { // Developer Guide
      type: 'category',
      label: 'Roadmaps for Future Features',
      link: {
        type: 'generated-index',
        title: 'Roadmaps for Future Features',
        //description: '',
        slug: '/future-features',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'future-features',
        },
      ],
    },
    { // Repo READMEs
      type: 'doc',
      id: 'list_READMEs',
      label: 'README List',
    },
    { // Additional Documentation Ideas
      type: 'doc',
      id: 'ideas',
      label: 'Additional Documentation Ideas',
    },
  ],
  deep_dives: [
    {
      type: 'category',
      label: 'Technical Deep Dives',
      link: {
        type: 'generated-index',
        title: 'Technical Deep Dives',
        slug: '/deep-dives',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'deep-dives',
        },
      ],
    },
  ],
  code_ref: [
    { // Backend
      type: 'category',
      label: 'Backend',
      link: {
        type: 'generated-index',
        title: 'Backend Code Reference',
        slug: '/code_ref/backend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/backend',
        },
      ],
    },
    { // Frontend
      type: 'category',
      label: 'Frontend',
      link: {
        type: 'generated-index',
        title: 'Frontend Code Reference',
        slug: '/code_ref/frontend',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/frontend',
        },
      ],
    },
    { // Shared
      type: 'category',
      label: 'Shared',
      link: {
        type: 'generated-index',
        title: 'Shared Module Code Reference',
        slug: '/code_ref/shared',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/shared/shared',
        },
      ],
    },
    { // Examples
      type: 'category',
      label: 'Examples',
      link: {type: 'doc', id: 'code_ref/examples/index'},
      items: ['code_ref/examples/basic_usage.py', 'code_ref/examples/custom_operation.py'],
    },
    { // Scripts
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts Code Reference',
        slug: '/code_ref/scripts',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'code_ref/scripts',
        },
      ],
    },
  ],
};

export default sidebars;
